apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: sumuduliyan/index-web
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80